(*
 Autogenerated by Thrift Compiler (0.11.0)

 DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING
*)

open Thrift
open Newt_types

class virtual iface :
object
  method virtual add : Int32.t option -> Int32.t
end

class client : Protocol.t -> Protocol.t -> 
object
  method add : Int32.t -> Int32.t
end

class processor : iface ->
object
  inherit Processor.t

  val processMap : (string, int * Protocol.t * Protocol.t -> unit) Hashtbl.t
  method process : Protocol.t -> Protocol.t -> bool
end

